using System;
using System.Runtime.InteropServices;
/// <summary>
/// This file was autogenerated by openCONFIGURATOR-1.4.1 on 18-Mar-2015 16:10:13
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 4)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public byte CN1_M00_DigitalInput_00h_AU8_DigitalInput01;
		[FieldOffset(1)]
		public byte CN1_M00_DigitalInput_00h_AU8_DigitalInput02;
		[FieldOffset(2)]
		public byte PADDING_VAR_1;
		[FieldOffset(3)]
		public byte PADDING_VAR_2;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 4)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public byte CN1_M00_DigitalOutput_00h_AU8_DigitalOutput01;
		[FieldOffset(1)]
		public byte CN1_M00_DigitalOutput_00h_AU8_DigitalOutput02;
		[FieldOffset(2)]
		public byte PADDING_VAR_1;
		[FieldOffset(3)]
		public byte PADDING_VAR_2;
	}
}
