/* This file was autogenerated by openCONFIGURATOR-1.4.1 on 18-Mar-2015 15:54:38 */
#ifndef XAP_h
#define XAP_h

# define COMPUTED_PI_OUT_SIZE 4
typedef struct
{
    unsigned CN1_M00_DigitalInput_00h_AU12_DigitalInput:12;
    unsigned CN1_M00_DigitalInput_00h_AU8_DigitalInput02:4;
    unsigned PADDING_VAR_1 : 16;
} PI_OUT;

# define COMPUTED_PI_IN_SIZE 4
typedef struct
{
    unsigned CN1_M00_DigitalOutput_00h_AU12_DigitalOutput:12;
    unsigned CN1_M00_DigitalOutput_00h_AU8_DigitalOutput02:4;
    unsigned PADDING_VAR_1 : 16;
} PI_IN;

#endif